/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    industries: Industry;
    'industry-sectors': IndustrySector;
    'why-us-points': WhyUsPoint;
    values: Value;
    'operating-approach-steps': OperatingApproachStep;
    credentials: Credential;
    'training-courses': TrainingCourse;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    'industry-sectors': IndustrySectorsSelect<false> | IndustrySectorsSelect<true>;
    'why-us-points': WhyUsPointsSelect<false> | WhyUsPointsSelect<true>;
    values: ValuesSelect<false> | ValuesSelect<true>;
    'operating-approach-steps': OperatingApproachStepsSelect<false> | OperatingApproachStepsSelect<true>;
    credentials: CredentialsSelect<false> | CredentialsSelect<true>;
    'training-courses': TrainingCoursesSelect<false> | TrainingCoursesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    footer: Footer;
    'contact-page': ContactPage;
    'training-page': TrainingPage;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'training-page': TrainingPageSelect<false> | TrainingPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Used to build the URL (/services/{slug}) and to join this service across all three tabs below.
   */
  slug: string;
  /**
   * Display order across the site — lower numbers first.
   */
  order: number;
  icon:
    | 'Activity'
    | 'ChartColumn'
    | 'ClipboardCheck'
    | 'Cpu'
    | 'Dna'
    | 'Droplet'
    | 'Droplets'
    | 'Factory'
    | 'FileText'
    | 'Flame'
    | 'FlaskConical'
    | 'Gauge'
    | 'Globe'
    | 'Handshake'
    | 'HardHat'
    | 'Landmark'
    | 'Leaf'
    | 'Link2'
    | 'Mail'
    | 'MapPin'
    | 'Microscope'
    | 'Mountain'
    | 'Phone'
    | 'Settings2'
    | 'Shield'
    | 'ShieldCheck'
    | 'Wrench'
    | 'Zap';
  /**
   * Short homepage card title, e.g. "Operations".
   */
  title: string;
  bullets: {
    value: string;
    id?: string | null;
  }[];
  /**
   * Hex color, e.g. #0B7A53
   */
  accentColor: string;
  /**
   * e.g. "Operate better"
   */
  tagline: string;
  /**
   * Long title for the /services listing band and detail-page hero, e.g. "Operations, Process & Environmental Performance".
   */
  fullTitle: string;
  intro: string;
  checklist: {
    value: string;
    id?: string | null;
  }[];
  scope: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  deliverables: string;
  outcomes: string;
  whoWeWorkWith: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  /**
   * Stable identifier for the homepage tab/accessibility ids — not a URL.
   */
  tabId: string;
  /**
   * Display order across the site — lower numbers first.
   */
  order: number;
  icon:
    | 'Activity'
    | 'ChartColumn'
    | 'ClipboardCheck'
    | 'Cpu'
    | 'Dna'
    | 'Droplet'
    | 'Droplets'
    | 'Factory'
    | 'FileText'
    | 'Flame'
    | 'FlaskConical'
    | 'Gauge'
    | 'Globe'
    | 'Handshake'
    | 'HardHat'
    | 'Landmark'
    | 'Leaf'
    | 'Link2'
    | 'Mail'
    | 'MapPin'
    | 'Microscope'
    | 'Mountain'
    | 'Phone'
    | 'Settings2'
    | 'Shield'
    | 'ShieldCheck'
    | 'Wrench'
    | 'Zap';
  label: string;
  description: string;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-sectors".
 */
export interface IndustrySector {
  id: number;
  /**
   * Display order across the site — lower numbers first.
   */
  order: number;
  icon:
    | 'Activity'
    | 'ChartColumn'
    | 'ClipboardCheck'
    | 'Cpu'
    | 'Dna'
    | 'Droplet'
    | 'Droplets'
    | 'Factory'
    | 'FileText'
    | 'Flame'
    | 'FlaskConical'
    | 'Gauge'
    | 'Globe'
    | 'Handshake'
    | 'HardHat'
    | 'Landmark'
    | 'Leaf'
    | 'Link2'
    | 'Mail'
    | 'MapPin'
    | 'Microscope'
    | 'Mountain'
    | 'Phone'
    | 'Settings2'
    | 'Shield'
    | 'ShieldCheck'
    | 'Wrench'
    | 'Zap';
  title: string;
  description: string;
  capabilities: {
    value: string;
    id?: string | null;
  }[];
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why-us-points".
 */
export interface WhyUsPoint {
  id: number;
  /**
   * Display order across the site — lower numbers first.
   */
  order: number;
  icon:
    | 'Activity'
    | 'ChartColumn'
    | 'ClipboardCheck'
    | 'Cpu'
    | 'Dna'
    | 'Droplet'
    | 'Droplets'
    | 'Factory'
    | 'FileText'
    | 'Flame'
    | 'FlaskConical'
    | 'Gauge'
    | 'Globe'
    | 'Handshake'
    | 'HardHat'
    | 'Landmark'
    | 'Leaf'
    | 'Link2'
    | 'Mail'
    | 'MapPin'
    | 'Microscope'
    | 'Mountain'
    | 'Phone'
    | 'Settings2'
    | 'Shield'
    | 'ShieldCheck'
    | 'Wrench'
    | 'Zap';
  title: string;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "values".
 */
export interface Value {
  id: number;
  /**
   * Display order across the site — lower numbers first.
   */
  order: number;
  icon:
    | 'Activity'
    | 'ChartColumn'
    | 'ClipboardCheck'
    | 'Cpu'
    | 'Dna'
    | 'Droplet'
    | 'Droplets'
    | 'Factory'
    | 'FileText'
    | 'Flame'
    | 'FlaskConical'
    | 'Gauge'
    | 'Globe'
    | 'Handshake'
    | 'HardHat'
    | 'Landmark'
    | 'Leaf'
    | 'Link2'
    | 'Mail'
    | 'MapPin'
    | 'Microscope'
    | 'Mountain'
    | 'Phone'
    | 'Settings2'
    | 'Shield'
    | 'ShieldCheck'
    | 'Wrench'
    | 'Zap';
  title: string;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operating-approach-steps".
 */
export interface OperatingApproachStep {
  id: number;
  /**
   * Both the displayed step number and the sort order.
   */
  step: number;
  title: string;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials".
 */
export interface Credential {
  id: number;
  /**
   * Display order across the site — lower numbers first.
   */
  order: number;
  icon:
    | 'Activity'
    | 'ChartColumn'
    | 'ClipboardCheck'
    | 'Cpu'
    | 'Dna'
    | 'Droplet'
    | 'Droplets'
    | 'Factory'
    | 'FileText'
    | 'Flame'
    | 'FlaskConical'
    | 'Gauge'
    | 'Globe'
    | 'Handshake'
    | 'HardHat'
    | 'Landmark'
    | 'Leaf'
    | 'Link2'
    | 'Mail'
    | 'MapPin'
    | 'Microscope'
    | 'Mountain'
    | 'Phone'
    | 'Settings2'
    | 'Shield'
    | 'ShieldCheck'
    | 'Wrench'
    | 'Zap';
  title: string;
  subtitle: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-courses".
 */
export interface TrainingCourse {
  id: number;
  /**
   * Used to build the URL (/training/{slug}).
   */
  slug: string;
  /**
   * Position in the portfolio — drives ordering and the "Course N of 8" hero label.
   */
  courseNumber: number;
  title: string;
  /**
   * Integrated Program offerings use "Program" wording and heavier visual weight throughout.
   */
  category: 'Short Course' | 'Applied Course' | 'Integrated Program';
  /**
   * Indicative total hours, e.g. "~15 h".
   */
  duration: string;
  moduleCount: number;
  /**
   * One concise value statement for the landing-page card.
   */
  summary: string;
  /**
   * Only the first five are shown on the landing-page card.
   */
  keyAreas: {
    value: string;
    id?: string | null;
  }[];
  /**
   * One entry per paragraph.
   */
  about: {
    value: string;
    id?: string | null;
  }[];
  /**
   * The "What You Will Learn" outcomes.
   */
  learn: {
    value: string;
    id?: string | null;
  }[];
  curriculum: {
    number: number;
    title: string;
    /**
     * Indicative module time, e.g. "~2.5 h".
     */
    duration: string;
    topics: {
      value: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  /**
   * The "Who Should Attend" roles.
   */
  audience: {
    value: string;
    id?: string | null;
  }[];
  prerequisites: {
    value: string;
    id?: string | null;
  }[];
  /**
   * e.g. "No prior formal training ... is required."
   */
  prereqNote: string;
  practicalIntro: string;
  practicalItems: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  /**
   * Integrated Programs only — the named capstone deliverable. Leave blank for Courses.
   */
  capstoneTitle?: string | null;
  /**
   * The applied case study / capstone scenario.
   */
  caseParagraphs: {
    value: string;
    id?: string | null;
  }[];
  /**
   * Ordered steps of the applied workflow.
   */
  workflow: {
    value: string;
    id?: string | null;
  }[];
  /**
   * Contents of the final deliverable. Leave empty where not applicable.
   */
  finalDeliverables?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  resourcesNote: string;
  resources: {
    value: string;
    id?: string | null;
  }[];
  gainIntro: string;
  gains: {
    value: string;
    id?: string | null;
  }[];
  /**
   * Areas of application — not specialisation claims.
   */
  industries: {
    value: string;
    id?: string | null;
  }[];
  finalCtaTitle: string;
  finalCtaDescription: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'industry-sectors';
        value: number | IndustrySector;
      } | null)
    | ({
        relationTo: 'why-us-points';
        value: number | WhyUsPoint;
      } | null)
    | ({
        relationTo: 'values';
        value: number | Value;
      } | null)
    | ({
        relationTo: 'operating-approach-steps';
        value: number | OperatingApproachStep;
      } | null)
    | ({
        relationTo: 'credentials';
        value: number | Credential;
      } | null)
    | ({
        relationTo: 'training-courses';
        value: number | TrainingCourse;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  order?: T;
  icon?: T;
  title?: T;
  bullets?:
    | T
    | {
        value?: T;
        id?: T;
      };
  accentColor?: T;
  tagline?: T;
  fullTitle?: T;
  intro?: T;
  checklist?:
    | T
    | {
        value?: T;
        id?: T;
      };
  scope?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  deliverables?: T;
  outcomes?: T;
  whoWeWorkWith?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  tabId?: T;
  order?: T;
  icon?: T;
  label?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-sectors_select".
 */
export interface IndustrySectorsSelect<T extends boolean = true> {
  order?: T;
  icon?: T;
  title?: T;
  description?: T;
  capabilities?:
    | T
    | {
        value?: T;
        id?: T;
      };
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why-us-points_select".
 */
export interface WhyUsPointsSelect<T extends boolean = true> {
  order?: T;
  icon?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "values_select".
 */
export interface ValuesSelect<T extends boolean = true> {
  order?: T;
  icon?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operating-approach-steps_select".
 */
export interface OperatingApproachStepsSelect<T extends boolean = true> {
  step?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials_select".
 */
export interface CredentialsSelect<T extends boolean = true> {
  order?: T;
  icon?: T;
  title?: T;
  subtitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-courses_select".
 */
export interface TrainingCoursesSelect<T extends boolean = true> {
  slug?: T;
  courseNumber?: T;
  title?: T;
  category?: T;
  duration?: T;
  moduleCount?: T;
  summary?: T;
  keyAreas?:
    | T
    | {
        value?: T;
        id?: T;
      };
  about?:
    | T
    | {
        value?: T;
        id?: T;
      };
  learn?:
    | T
    | {
        value?: T;
        id?: T;
      };
  curriculum?:
    | T
    | {
        number?: T;
        title?: T;
        duration?: T;
        topics?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  audience?:
    | T
    | {
        value?: T;
        id?: T;
      };
  prerequisites?:
    | T
    | {
        value?: T;
        id?: T;
      };
  prereqNote?: T;
  practicalIntro?: T;
  practicalItems?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  capstoneTitle?: T;
  caseParagraphs?:
    | T
    | {
        value?: T;
        id?: T;
      };
  workflow?:
    | T
    | {
        value?: T;
        id?: T;
      };
  finalDeliverables?:
    | T
    | {
        value?: T;
        id?: T;
      };
  resourcesNote?: T;
  resources?:
    | T
    | {
        value?: T;
        id?: T;
      };
  gainIntro?: T;
  gains?:
    | T
    | {
        value?: T;
        id?: T;
      };
  industries?:
    | T
    | {
        value?: T;
        id?: T;
      };
  finalCtaTitle?: T;
  finalCtaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  navLinks: {
    href: string;
    label: string;
    id?: string | null;
  }[];
  ctaHref: string;
  ctaLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  servicesLinks: {
    href: string;
    label: string;
    id?: string | null;
  }[];
  legalLinks: {
    href: string;
    label: string;
    id?: string | null;
  }[];
  contactEmail: string;
  contactPhone: string;
  addresses: {
    label: string;
    value: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  contactInfoItems: {
    icon:
      | 'Activity'
      | 'ChartColumn'
      | 'ClipboardCheck'
      | 'Cpu'
      | 'Dna'
      | 'Droplet'
      | 'Droplets'
      | 'Factory'
      | 'FileText'
      | 'Flame'
      | 'FlaskConical'
      | 'Gauge'
      | 'Globe'
      | 'Handshake'
      | 'HardHat'
      | 'Landmark'
      | 'Leaf'
      | 'Link2'
      | 'Mail'
      | 'MapPin'
      | 'Microscope'
      | 'Mountain'
      | 'Phone'
      | 'Settings2'
      | 'Shield'
      | 'ShieldCheck'
      | 'Wrench'
      | 'Zap';
    label: string;
    value: string;
    id?: string | null;
  }[];
  expectSteps: {
    /**
     * e.g. "01" — stored as text to keep the leading zero.
     */
    step: string;
    title: string;
    description: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-page".
 */
export interface TrainingPage {
  id: number;
  heroTitle: string;
  heroDescription: string;
  positioning: {
    value: string;
    id?: string | null;
  }[];
  /**
   * Groups the portfolio on the landing page, in this order. `category` must match the value used on each course.
   */
  categories: {
    category: 'Short Course' | 'Applied Course' | 'Integrated Program';
    /**
     * Plural heading, e.g. "Short Courses".
     */
    label: string;
    caption: string;
    id?: string | null;
  }[];
  deliveryOptions: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  corporateTitle: string;
  corporateDescription: string;
  finalCtaTitle: string;
  finalCtaDescription: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  navLinks?:
    | T
    | {
        href?: T;
        label?: T;
        id?: T;
      };
  ctaHref?: T;
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  servicesLinks?:
    | T
    | {
        href?: T;
        label?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        href?: T;
        label?: T;
        id?: T;
      };
  contactEmail?: T;
  contactPhone?: T;
  addresses?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  contactInfoItems?:
    | T
    | {
        icon?: T;
        label?: T;
        value?: T;
        id?: T;
      };
  expectSteps?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-page_select".
 */
export interface TrainingPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  positioning?:
    | T
    | {
        value?: T;
        id?: T;
      };
  categories?:
    | T
    | {
        category?: T;
        label?: T;
        caption?: T;
        id?: T;
      };
  deliveryOptions?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  corporateTitle?: T;
  corporateDescription?: T;
  finalCtaTitle?: T;
  finalCtaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}